# Generated by Django 2.1.7 on 2019-03-18 02:28

import common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ulid.api


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', common.models.ULIDField(default=ulid.api.new, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('amount', models.IntegerField(verbose_name='send value')),
                ('message', models.CharField(blank=True, max_length=255, null=True, verbose_name='message')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_from', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_to', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
