# Generated by Django 2.1.5 on 2019-02-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idm',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='card name'),
        ),
    ]
