# Generated by Django 2.1.5 on 2019-02-11 16:50

import common.models
from django.conf import settings
from django.db import migrations, models
import ulid.api


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', common.models.ULIDField(default=ulid.api.new, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('name', models.CharField(max_length=30, verbose_name='merchant name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('accounts', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
