# Generated by Django 2.1.5 on 2019-02-11 06:52

import common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ulid.api


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', common.models.ULIDField(default=ulid.api.new, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('payment_method', models.IntegerField(choices=[(0, 'FeliCa Card'), (1, 'QR Code')], verbose_name='payment method')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='merchants.Merchant')),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
