# Generated by Django 2.1.7 on 2019-03-17 06:45

import common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ulid.api


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_upload', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', common.models.ULIDField(default=ulid.api.new, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('name', models.CharField(max_length=30, verbose_name='merchant name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('accounts', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='media_upload.Image', verbose_name='icon')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
